language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest pytest -v
#  - python -m unittest pytest2 -v

#notifications:
#  email:
#    recipients:
#    - katya.grohotova.4@gmail.com
#    on_success: never
#    on_failure: always