language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

#before_script: cd pytest/

script:
  - python -m unittest test_RNN

#notifications:
#  email:
#    recipients:
#    - katya.grohotova.4@gmail.com
#    on_success: never
#    on_failure: always